apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 427735392661.dkr.ecr.ap-south-1.amazonaws.com/images:8250b5f8b351c1ae5189a9f96c2ce3e76d8a0840
          ports:
            - containerPort: 80
