apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unicorn-dashboard
  namespace: unicorn
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: unicorn.lovestoblog.com
    http:
      paths:
      - path: /
        pathType: Exact  
        backend:
          service:
            name: nginx-service
            port:
              number: 80