apiVersion: v1
kind: Service
metadata:
  name: aws-eks-service
spec:
  selector:
    app: aws-eks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  loadBalancerIP: 192.168.49.2
  type: LoadBalancer
